# Generated by Django 4.0.5 on 2022-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
