# Generated by Django 4.0.5 on 2022-06-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0002_alter_user_detail_image_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
