# Generated by Django 4.0.5 on 2022-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0004_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='expired_time',
            field=models.DateTimeField(null=True),
        ),
    ]
