# Generated by Django 3.2.9 on 2022-06-21 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_alter_bread_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountt', '0006_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Favorite_Breads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.bread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
