# Generated by Django 4.0.5 on 2022-07-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0008_delete_user_favorite_breads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('limit_buy', models.IntegerField(default=15)),
                ('limit_day', models.IntegerField(default=7000)),
            ],
        ),
    ]
