# Generated by Django 4.0.5 on 2022-07-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0010_alter_setting_is_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='phone_number',
        ),
    ]
