# Generated by Django 4.0.5 on 2022-08-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0015_alter_sign_up_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('mashhad', 'مشهد')], default='mashhad', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='pelak',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('khorasan_razavi', 'خراسان رضوی')], default='khorasan_razavi', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='vahed',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
