# Generated by Django 4.0.5 on 2022-10-16 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0017_authenticated_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticated_code',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
