# Generated by Django 4.0.5 on 2023-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0020_alter_address_vahed'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
