# Generated by Django 4.0.5 on 2022-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_cart_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=10)),
                ('dicount_percent', models.IntegerField(default=1)),
                ('max_price_dicount', models.IntegerField(default=0)),
            ],
        ),
    ]
