# Generated by Django 4.2.7 on 2023-12-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0006_alter_bread_attr_bread'),
        ('order', '0017_alter_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='bread_attr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bread.bread_attr'),
        ),
    ]
