# Generated by Django 4.2.7 on 2023-12-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_cart_item_bread_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
