# Generated by Django 4.2.7 on 2023-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_cart_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bag',
            field=models.CharField(choices=[('1', 'کاغذی'), ('2', 'پلاستیکی')], default='1', max_length=1),
        ),
    ]
