# Generated by Django 4.0.5 on 2022-07-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0007_user_favorite_breads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Favorite_Breads',
        ),
    ]
