# Generated by Django 4.0.5 on 2022-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0009_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
    ]
