# Generated by Django 4.0.5 on 2022-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0013_alter_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
