# Generated by Django 4.0.5 on 2022-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0014_alter_code_code_alter_code_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
