# Generated by Django 4.0.5 on 2023-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0019_alter_address_vahed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='vahed',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
