# Generated by Django 4.0.5 on 2023-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0021_address_lat_address_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pelak',
            field=models.IntegerField(null=True),
        ),
    ]
