# Generated by Django 4.0.5 on 2023-01-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0022_alter_address_pelak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='vahed',
            field=models.IntegerField(null=True),
        ),
    ]
