# Generated by Django 4.0.5 on 2023-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountt', '0025_rename_city_address_city_v_remove_address_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_v',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state_v',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('ma', 'مشیسب')], default='mashhad', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('ma', 'مشیسب')], default='khorasan_razavi', max_length=50),
        ),
    ]
