# Generated by Django 4.0.5 on 2022-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
