# Generated by Django 4.0.5 on 2022-06-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cart_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='product_id',
            new_name='bread',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
