# Generated by Django 4.0.5 on 2022-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('1', 'حضوری'), ('2', 'پیک')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='order.cart'),
        ),
    ]
