# Generated by Django 4.0.5 on 2022-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_delivery_mode_alter_cart_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('1', 'حضوری'), ('2', 'پیک')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
