# Generated by Django 4.0.5 on 2022-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_cart_is_delivered_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_mode',
            field=models.CharField(choices=[('1', 'حضوری'), ('2', 'پیک')], default='1', max_length=1),
        ),
    ]
