# Generated by Django 4.0.5 on 2022-07-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': [('can_view_cart', 'میتونه سفارش ها رو مشاهده کنه'), ('can_access_produce_section', 'دسترسی به بخش تولید نان ')]},
        ),
    ]
