# Generated by Django 4.0.5 on 2022-08-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_discount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='price_after_max_price',
            field=models.IntegerField(default=0),
        ),
    ]
