# Generated by Django 4.0.5 on 2022-09-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_discount_price_after_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='order.discount'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=50),
        ),
    ]
